### ISSUE TITLE
DRP causes terraria.exe to not close

### ISSUE THREAD

**Issue by Xetaxheb** [PurplefinNeptuna/DiscordRP-tModLoader#3]
To replicate:

Run terraria with DRP enabled
Close terraria with normal main menu exit game
Check task manager

It might matter that i'm in invisible mode on discord
It might also matter that i'm offline on steam (not piracy or anything, just normal steam owned game but i'm in offline mode)

**Comment by PurplefinNeptuna** [comment]
@Xetaxheb did you use latest version?, because that bug happened in v0.4 and earlier

also i can't replicate with current version
did you reload mods before exit?

**Comment by PurplefinNeptuna** [comment]
```cs
public override void Unload()
{
	RPControl.Disable();
}
```
This code is responsible to stopping Rich Presence service, so maybe the mod is didn't unloaded properly

**Comment by PurplefinNeptuna** [comment]
I think it's solved with newer version of this mod
