### ISSUE TITLE
No Linux Support

### ISSUE THREAD

**Issue by ghost** [PurplefinNeptuna/DiscordRP-tModLoader#4]
[Loading Errors.txt](https://github.com/PurplefinNeptuna/DiscordRP-tModLoader/files/1800859/Loading.Errors.txt)
This error is sad. :c Is there any way to add Linux support? It would be really cool!

**Comment by PurplefinNeptuna** [comment]
it's now kinda supported, except if terraria or discord is sandboxed (using discord from snap)
