### ISSUE TITLE
Presence in multiplayer is very delayed.

### ISSUE THREAD

**Issue by nickian563** [PurplefinNeptuna/DiscordRP-tModLoader#5]
The presence works perfectly in singleplayer, but in multiplayer it does not. The presence is always either still in the main menu or very delayed. (Sometimes it works.)
![image](https://user-images.githubusercontent.com/30329887/68073358-ba432e80-fd65-11e9-9be8-fcb5602c9452.png)
![image](https://user-images.githubusercontent.com/30329887/68073363-c5965a00-fd65-11e9-9c21-b542314c4983.png)

**Comment by PurplefinNeptuna** [comment]
I think it happened because old logic that broken in multiplayer
now I rewrite all the code, and I think it handle multiplayer better
not closing the issues because not tested yet

**Comment by PurplefinNeptuna** [comment]
Now fixed in newest version, it actually caused by dumb bugs
